In [20]:
import pandas as pd

df = pd.read_excel("BCG_GenAI_Financial_Data_Extraction_Example.xlsx", sheet_name="Extracted Data")

In [21]:
df

,Company Name,Ticker,Fiscal Year,Fiscal Year End,Total Revenue,Net Income,Total Assets,Total Liabilities,Cash Flow from Operating Activities,Revenue Growth (%),Net Income Growth (%),Operating Cash Flow Growth (%),Profit Margin (%),Liabilities / Assets (%),Source URL
0,Microsoft,MSFT,2023,2023-06-30,211915,72361,411976,205753,87582,NaN,NaN,NaN,0.341462,0.499430,https://www.microsoft.com/investor/reports/ar2...
1,Microsoft,MSFT,2024,2024-06-30,245122,88136,512163,243686,118548,0.156700,0.218004,0.353566,0.359560,0.475798,https://www.microsoft.com/investor/reports/ar2...
2,Microsoft,MSFT,2025,2025-06-30,281724,101832,619003,275524,136162,0.149322,0.155396,0.148581,0.361460,0.445109,https://www.microsoft.com/investor/reports/ar2...
3,Tesla,TSLA,2023,2023-12-31,96773,14974,106618,43009,13256,NaN,NaN,NaN,0.154733,0.403393,https://stocklight.com/stocks/us/nasdaq-tsla/t...
4,Tesla,TSLA,2024,2024-12-31,97690,7153,122070,48390,14923,0.009476,-0.522305,0.125754,0.073221,0.396412,https://stocklight.com/stocks/us/nasdaq-tsla/t...
5,Tesla,TSLA,2025,2025-12-31,94827,3855,137806,54941,14747,-0.029307,-0.461065,-0.011794,0.040653,0.398684,https://stocklight.com/stocks/us/nasdaq-tsla/t...
6,Apple,AAPL,2023,2023-09-30,383285,96995,352583,290437,110543,NaN,NaN,NaN,0.253062,0.823741,https://www.sec.gov/Archives/edgar/data/320193...
7,Apple,AAPL,2024,2024-09-28,391035,93736,364980,308030,118254,0.020220,-0.033600,0.069756,0.239713,0.843964,https://www.sec.gov/Archives/edgar/data/320193...
8,Apple,AAPL,2025,2025-09-27,416161,112010,359241,285508,111482,0.064255,0.194952,-0.057267,0.269151,0.794753,https://www.sec.gov/Archives/edgar/data/320193...

In [23]:
df = df.sort_values(['Company Name', 'Fiscal Year'])
df

,Company Name,Ticker,Fiscal Year,Fiscal Year End,Total Revenue,Net Income,Total Assets,Total Liabilities,Cash Flow from Operating Activities,Revenue Growth (%),Net Income Growth (%),Operating Cash Flow Growth (%),Profit Margin (%),Liabilities / Assets (%),Source URL
6,Apple,AAPL,2023,2023-09-30,383285,96995,352583,290437,110543,NaN,NaN,NaN,0.253062,0.823741,https://www.sec.gov/Archives/edgar/data/320193...
7,Apple,AAPL,2024,2024-09-28,391035,93736,364980,308030,118254,0.020220,-0.033600,0.069756,0.239713,0.843964,https://www.sec.gov/Archives/edgar/data/320193...
8,Apple,AAPL,2025,2025-09-27,416161,112010,359241,285508,111482,0.064255,0.194952,-0.057267,0.269151,0.794753,https://www.sec.gov/Archives/edgar/data/320193...
0,Microsoft,MSFT,2023,2023-06-30,211915,72361,411976,205753,87582,NaN,NaN,NaN,0.341462,0.499430,https://www.microsoft.com/investor/reports/ar2...
1,Microsoft,MSFT,2024,2024-06-30,245122,88136,512163,243686,118548,0.156700,0.218004,0.353566,0.359560,0.475798,https://www.microsoft.com/investor/reports/ar2...
2,Microsoft,MSFT,2025,2025-06-30,281724,101832,619003,275524,136162,0.149322,0.155396,0.148581,0.361460,0.445109,https://www.microsoft.com/investor/reports/ar2...
3,Tesla,TSLA,2023,2023-12-31,96773,14974,106618,43009,13256,NaN,NaN,NaN,0.154733,0.403393,https://stocklight.com/stocks/us/nasdaq-tsla/t...
4,Tesla,TSLA,2024,2024-12-31,97690,7153,122070,48390,14923,0.009476,-0.522305,0.125754,0.073221,0.396412,https://stocklight.com/stocks/us/nasdaq-tsla/t...
5,Tesla,TSLA,2025,2025-12-31,94827,3855,137806,54941,14747,-0.029307,-0.461065,-0.011794,0.040653,0.398684,https://stocklight.com/stocks/us/nasdaq-tsla/t...

In [26]:
df['Revenue Growth (%)'] = (df.groupby('Company Name')['Total Revenue'].pct_change() * 100)
df['Revenue Growth (%)']

6          NaN
7     2.021994
8     6.425512
0          NaN
1    15.669962
2    14.932156
3          NaN
4     0.947578
5    -2.930699
Name: Revenue Growth (%), dtype: float64

In [28]:
df['Net Income Growth (%)'] = (df.groupby('Company Name')['Net Income'].pct_change() * 100)

df['Net Income Growth (%)']

6          NaN
7    -3.359967
8    19.495178
0          NaN
1    21.800417
2    15.539621
3          NaN
4   -52.230533
5   -46.106529
Name: Net Income Growth (%), dtype: float64

In [30]:
summary = df.groupby('Company Name').agg({'Revenue Growth (%)': 'mean', 'Net Income Growth (%)': 'mean'}).round(2)
print("\nAverage Growth Rates (%)")
print(summary)

Average Growth Rates (%)
              Revenue Growth (%)  Net Income Growth (%)
Company Name
Apple                       4.22                   8.07
Microsoft                  15.30                  18.67
Tesla                      -0.99                 -49.17